### ISSUE TITLE
Automatically Generated Facility Identifier Using the Luhn Algorithm

### ISSUE THREAD

**Issue by steesdale** [facilityregistry/reference_implementation#1]
The MOHSW TZ has request an automatically generated facility identifier as an enhancement to ResourceMap that includes a check digit.  The data specification as described by the MOH is included below. 

Definition:  auto-generated sequential number allocated to each facility when  it is added to the master list. It is allocated by the central facility registry and provided back to the health community for subsequent use. This replaces the old Registration ID

Data Rules:  the facility ID follows the following format:  xxxxxx-y, where xxxxxx is a six digit numeric code, and y is a one digit check digit, generated via the Luhn Algorithm (mod 10) see: http://en.wikipedia.org/wiki/Luhn_algorithm for more information; where there are no leading zeros for IDs, starting at 100001-7.

Example:  123456-6

Proposed Solution:  A plug-in which can be incorporated into a particular implementation as needed to facilitate the generation of the unique facility id.

**Comment by mverzilli** [comment]
A couple of questions regarding this:

1) What was the "old Registration ID"? Where was it used and by whom? 

2) How does this relate to the facility's UUID? I feel there's some functional overlap between the current UUIDs and a hypothetical Luhn ID. Would this new id be just a special kind of external identifier for the facility?

**Comment by steesdale** [comment]
1) The old Registration ID was an old facility identifier only applied to a subset of facilities in Tz.  

2) My understanding is that the UUID is an internal ID to ResourceMap that isn't displayed through the ResourceMap user interface.  The Luhn ID would a more public unique identifier that might be entered by hand on a paper form, etc... @edjez  Is this correct?

**Comment by edjez** [comment]
@steesdale correct

**Comment by mverzilli** [comment]
Instead of adding a new plugin, what do you think of integrating this feature to the existing "Identifier" field type? We still need to think through the implementation details, but I'm afraid that adding another field type with such similar semantics ("external id") may be a little confusing both for end users and developers.

**Comment by steesdale** [comment]
I think this sounds good.  A few considerations:

1) Would the field be editable during data entry or auto generated when a facility is created and then set in stone?   I would advocate for the later.  

2) Seems that this approach could allow for other automated algorithms or formats to be available in the future, too.  
 3) is it worth while distinguishing in a form field between an automatically generated Id and a manually entered id?

**Comment by edjez** [comment]
Editable is important as errors happen and facilities get re-id'd sometimes.
Therefore we can suggest one (the 'next' id - largest used + 1) and let the user adapt it.

**Comment by steesdale** [comment]
Ok, yes you are correct on that.  Let's keep as editable.

**Comment by mverzilli** [comment]
We've started working on this. This is the way we're approaching it:

1) We'll create a plugin that will provide a new field type "Luhn Identifier".

2) Luhn Identifier fields will be included in the "identifiers" field of facilities exposed through the FRED API.

3) If the user doesn't provide a value for a Luhn Identifier field, Resource Map will autogenerate a new one with format XXXXXX-Y, as specified above.

4) Luhn Identifiers will be editable, Resource Map will ensure their uniqueness within a collection and their compliance with the format XXXXXX-Y.

**Comment by mverzilli** [comment]
Done
