### ISSUE TITLE
The width of the data entry user interface is too small

### ISSUE THREAD

**Issue by steesdale** [facilityregistry/reference_implementation#10]
#### Issue Description

It has been observed in Tanzania that the user interface to enter data is too narrow which makes the process of entering larger numbers of data fields difficult.  This is complicated by any long field names that spill over into a second line of data.  It presents in a messy or difficult to easily skim manner. 

![screen shot 2013-07-16 at 12 17 50 pm](https://f.cloud.github.com/assets/3987608/806099/7ee674f2-ee33-11e2-97fd-4ed92d86941e.png)
#### Recommendation

We would like to open this feedback to the design and development process of Resource Map at large.  A few potential ideas to consider are: 
1. Option to expand data entry or data viewing section. 
2. Reduce extra sms labels

**Comment by steesdale** [comment]
It would be helpful for the formatting to also be consistent between viewing in map view a facility record , editing an existing record and creating a new record.  See some screen shots showing how they vary. For instance some fields wrap when editing a facility, and are justified at the same level when entering a new facility.  If we could expand the viewer, perhaps we could keep the majority of fields on only one line. 

![screen shot 2013-07-16 at 12 25 37 pm](https://f.cloud.github.com/assets/3987608/806223/0ca74ada-ee36-11e2-9c6d-6fbdbce2eb41.png)

![screen shot 2013-07-16 at 12 24 20 pm](https://f.cloud.github.com/assets/3987608/806224/0efe6656-ee36-11e2-8174-0d7c8ff689ed.png)

**Comment by mturi** [comment]
The display of the facility record in the upper screen shows the field label, caption and the values do we need to see them. For example Facility Type  Fac_Type: Dispensary

**Comment by mverzilli** [comment]
We've already addressed this. It's online at resmap-stg.instedd.org

**Comment by mturi** [comment]
Many thanks Mverzilli, Yes I see it looks excellent now
