### ISSUE TITLE
Permissions for Health Facility Name and GPS Coordinates

### ISSUE THREAD

**Issue by steesdale** [facilityregistry/reference_implementation#13]
#### Issue Description

Currently, you can't set specific user permissions for the facility name and GPS coordinates, as they are core fields included in any collection.  This results in some limitations as to controlling who can edit or change the name of a health facility. 
#### Recommendation

Include a default layer with Name and GPS coordinates that would allow for setting specific permissions by user.

**Comment by carohadad** [comment]
We implemented it as 2 different default layers, one with Name and one with Location.
