### ISSUE TITLE
Specify a Default Value in Single Select Form Fields

### ISSUE THREAD

**Issue by steesdale** [facilityregistry/reference_implementation#4]
#### Issue Description

In Tz there is an instance where it is desirous to allow for default values to be set for single-select fields.  This is to allow for improved curation of data by indicating that a field is "Ready for Review" by setting it as the default value, and then restricting access to edit that field to curators of the registry.   A new facility entered into the registry would then be automatically identified as to be reviewed by the next level of curation.  In the future, external applications could also be incorporated in addition to the registry to facilitate improve work flow management.
#### Recommendation

When creating a single select form field, optionally allow a user to specify one of the entries as the default value in single-select fields.

**Comment by steesdale** [comment]
Notes from Martin: A solution has been drafted now to allow for default values when designing a form field, but is currently going through QA testing.  Once that is completed they can deploy a new version.

**Comment by mverzilli** [comment]
Now that issue #7 (filtering by blank/empty/null values) is done, is this one really necessary? Right now, the default for all single select fields is "(no value)". That sounds reasonable for an initial value, and thanks to the new filters a user can focus on those that haven't been set yet.

**Comment by steesdale** [comment]
Checked in with Mturi and Niamh from Tanzania and they agree with your comments above.  We can put this on hold for now.  - Scott

**Comment by mverzilli** [comment]
We won't implement this one because it's not really necessary given now Resource Map let's you filter by null/empty values.
