### ISSUE TITLE
Hierarchy Form Fields Require Unique Node Names

### ISSUE THREAD

**Issue by steesdale** [facilityregistry/reference_implementation#5]
#### Issue Description

When uploading a csv to generate a hierarchy structure, if the name of the hierarchy node is the same an error is produced despite each value having a UniqueID also associated with it.  The reported error is " Error Invalid Name, Hierarchy name should be unique..." see screenshot attached.

![hierarchy node names](https://f.cloud.github.com/assets/3987608/606160/0268ac12-cd25-11e2-8ff8-35328e8afeb8.png)

This bug was surfaced because Tz has an Admin hierarchy currently with approx 3500 values and there is name overlap at the more granular levels of the admin hierarchy. 
#### Recommendation

I would expect that as long as the ID is unique this should not produce an error.

**Comment by mverzilli** [comment]
The change to support duplicate names in hierarchies is not trivial. We're going to analize what it takes, but in the meantime, any disambiguation criteria could be made explicit in names to work around the issue. For example, you could append the name of the parent item between brackets: 

1) Nyarugenge => Nyarugenge
2) Bugesera => Nyarugenge

Item 1 could be turned into "Nyarugenge (Nyarugenge)"
Item 2 could be turned into "Nyarugenge (Bugesera)"
