### ISSUE TITLE
Can't Filter Data by Missing/Null Value

### ISSUE THREAD

**Issue by steesdale** [facilityregistry/reference_implementation#7]
#### Issue Description

When using the "refine results" option to filter data in a collection, there is no option to select for missing results or null.  It will be helpful to implementers to filter by missing or null results. 

![filter options](https://f.cloud.github.com/assets/3987608/619379/fa3591ec-cecb-11e2-981f-36443bd2f0ee.png)
#### Recommendation

Improve filter options to include an option for missing data.

**Comment by mverzilli** [comment]
Done. We'll ship it with Resource Map 2.2 in a couple of weeks.
