### ISSUE TITLE
Validate uniqueness of external identifiers within agency and context

### ISSUE THREAD

**Issue by mverzilli** [facilityregistry/reference_implementation#8]
Currently Resource Map takes external identifiers as they are provided by the user or clients of the API. 

We think it makes sense to require identifiers to be unique for a given agency and context.

Doing that would have at least one positive side effect: we would then be able to use them from the Import Wizard, as a sync hook. 

For example, by inspecting whether a facility with id 123, agency "foo" and context "bar" exists already in the collection, we could know whether the user's intent is to create a new facility or update an existing one.

**Comment by mverzilli** [comment]
@edjez, @steesdale , any thoughts on this?

**Comment by steesdale** [comment]
+1, I think this could be helpful to improve Import wizard functionality.  Particularly for the work that will be required by Jorge to reconcile multiple non-standardized facility lists into an MFL that may have varying external identifiers.  

A question: in the instance where an external ID is missing for a number of facilities, would that still be allowed during import and subsequent storage?  I think it would be common where an identifier is applied to only private or subsets of facilities meaning others outside the scope of an external ID would have no ID assigned.

**Comment by mverzilli** [comment]
Right. External ids are optional by default. We could allow them to have different behaviors if use cases arise. For example, we're implementing the Luhn identifier as an external id that behaves differently (it's autogenerated when missing, it has a special format and it has checksum digit).

**Comment by steesdale** [comment]
So it would only be unique if there was a value?

**Comment by mverzilli** [comment]
Exactly. The default behavior is:

1) When a facility is created
a) If an external id is set, RM validates its uniqueness (within a RM
collection).
b) If no external id is set, RM creates the facility without a value for it.

2) When a facility is updated
a) If an external id is set, RM validates its uniqueness and updates the
facility (note that the external id may or may not have changed).
b) If no external id is set, RM saves the facility without a value for it.

On Wed, Jun 26, 2013 at 5:08 PM, steesdale notifications@github.com wrote:

> So it would only be unique if there was a value?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/facilityregistry/reference_implementation/issues/8#issuecomment-20076199
> .

## 

Martín Verzilli
Manas Technology Solutions
[ar.phone] 5258.5240 #MVR(687)
[us.phone] 312.612.1050 #MVR(687)
[email] mverzilli@manas.com.ar
[web] www.manas.com.ar
[blog] weblogs.manas.com.ar/mverzilli

**Comment by carohadad** [comment]
Implemented.
All Identifiers values  must be unique within agency and context, but they (by default) are nulleables. Validations are performed in the updates via UI, ImportWizard and all APIs.
